# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0003_auto_20170220_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='questionnaire_mturk',
            new_name='mturk',
        ),
    ]
