# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0005_questionnaire_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='mturk',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
